project:
  type: website
  output-dir: docs

website:
  title: Lisa Chong
  favicon: /Users/lisa_chong/Library/CloudStorage/GoogleDrive-lisa.chong8594@gmail.com/My Drive/GitHub/lidach.github.io/add_files/Chong_logo.jpg
  page-navigation: true
  navbar:
    logo: /add_files/images/Chong_logo.jpeg
    left:
      - index.qmd
      - text: Research
        menu:
          - text: Data-limited length-based methods
            href: dllm.qmd
          - text: Florida bay scallop simulation
            href: scallop.qmd
          - text: Artificial reefs in socio-ecological fisheries
            href: ar_ses.qmd
          - text: Florida Largemouth Bass stocking simulation (in progress)
          - text: Artificial reef simulation models (in progress)
          - text: Gulf of Mexico red snapper (in progress)
          - text: Lake Whitefish stock assessment (in progress)
      - resources.qmd
      - cv.qmd
        
format:
  html: 
    theme:
      light: [cosmo, style.scss, light.scss]
      dark: [cosmo, style.scss, dark.scss]

editor: visual

