project:
  type: website
  output-dir: docs

website:
  title: Lisa Chong
  favicon: /Users/lisa_chong/Library/CloudStorage/GoogleDrive-lisa.chong8594@gmail.com/My Drive/GitHub/lidach.github.io/add_files/Chong_logo.jpg
  navbar:
    logo: /add_files/Chong_logo.jpeg
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV


format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

