project:
  type: website
  output-dir: docs

website:
  title: Lisa Chong
  favicon: /Users/lisa_chong/Library/CloudStorage/GoogleDrive-lisa.chong8594@gmail.com/My Drive/GitHub/lidach.github.io/add_files/Chong_logo.jpg
  page-navigation: true
  navbar:
    logo: /add_files/images/Chong_logo.jpeg
    left:
      - index.qmd
      - text: Research
        menu:
          - text: Data-limited length-based methods
            href: dllm.qmd
          - text: Bay scallop simulation
            href: scallop.qmd
          - text: Artificial reefs in socio-ecological fisheries
            href: ar_ses.qmd
          - text: Artificial reef simulation models (in progress)
      - cv.qmd
        
format:
  html:
    theme: cosmo
    css: style.css

editor: visual

