project:
  type: website
  output-dir: docs

website:
  title: Lisa Chong
  favicon: ./add_files/Chong_logo.jpg
  page-navigation: true
  navbar:
    logo: /add_files/images/Chong_logo.jpeg
    left:
      - index.qmd
      - text: Research
        menu:
          - text: Data-limited stock assessment
            href: dllm.qmd
          - text: Artificial reefs in socio-ecological fisheries
            href: ar_ses.qmd
          - text: Florida bay scallop simulation
            href: scallop.qmd
          - text: Gulf of Mexico red snapper
            href: rs.qmd
          - text: Gulf of Mexico greater amberjack (in progress)
          - text: Florida Largemouth Bass stocking simulation (in progress)
          - text: Artificial reef simulation models (in progress)
          - text: Lake Whitefish stock assessment (in progress)
      - resources.qmd
      - cv.qmd
        
format:
  html: 
    theme:
      light: [cosmo, style.scss, light.scss]
      dark: [cosmo, style.scss, dark.scss]

editor: visual

