---
title: "Examining the performance of alternative harvest regulations for short-lived taxa: A case study of Florida Bay scallop management"
css: style.css
---

Authors: Lisa Chong* (UF), Nicholas Fisch* (NOAA), John Scott Borsum (UF), Jennifer Granneman (FWC), Diana Perry (UF), Gabrielle Love (UF), Brittany Hall-Scharf (FL SeaGrant), Robert Botta (UF), Kai Lorenzen (UF), Edward Camp (UF), Zachary Siders (UF)

*shared first authorship

In this manuscript we explore the performance of current and alternative management regulations for a simulated recreational bay scallop fishery on the Gulf coast of Florida. The bay scallop recreational fishery in Florida offers an interesting case study on the management of short lived and semelparous taxa, a group of species whose unique life history may render classical fisheries management tools or regulations suboptimal. We first develop a simulation model representing a local Florida bay scallop fishery and use this model to evaluate alternative management regulations under various levels of exploitation and effort. 

![Map of Big Bend region of Florida (red rectangle in inset) depicting the five scalloping zones (A-E). Zone D (depicted in orange) was the area chosen for the baseline management regulations in this study and spans Levy, Citrus, and Hernando counties. The per person bag limit in gallons of whole scallops as well as the dates for the open and close of the scalloping season are provided in the table by zone. Note that zone C has a rolling bag limit that is 50% lower in the first 15 day of the season.](./add_files/images/scallop_fig1.png){fig-align="center" width="400" height="300"}

![Results of spawning output relative to unfished for the different management regulations simulated in this study under different starting levels of population exploitation (columns) and different assumptions about the level of effort expended between years (rows). The first row depicts a scenario with constant effort in each year of the simulation, where the second row depicts a scenario with effort doubling over the course of the 25-year simulation period. ](./add_files/images/scallop_fig2.jpg){fig-align="center" width="600" height="500"}

Our findings suggest that biologically designed regulations (e.g. later season or rolling bag limits), that ensured some bay scallop spawning prior to harvest, performed well across all simulated exploitation and effort levels on both ecological and socioeconomic metrics. Under greater simulated exploitation, these regulations clearly outperformed other regulations, but also performed no worse than other regulations under lower exploitation simulations.

Now published: <https://www.sciencedirect.com/science/article/abs/pii/S0165783623000760>

Code and workflow: <https://github.com/lidach/CampLabScallop>